
---
spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: false
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
app:
  datasource:
    jdbc-url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
